### ISSUE TITLE
Can't instantiate with an abstract method

### ISSUE THREAD

**Issue by YandongJi** [leggedrobotics/raisimGym#52]
Traceback (most recent call last):
  File "scripts/laikago_blind_locomotion.py", line 52, in <module>
    model.learn(total_timesteps=400000000, eval_every_n=50, log_dir=saver.data_dir, record_video=cfg['record_video'])
  File "/usr/local/lib/python3.5/dist-packages/raisim_gym-0.5.0-py3.5-linux-x86_64.egg/raisim_gym/algo/ppo2/ppo2.py", line 284, in learn
    runner = Runner(env=self.env, model=self, n_steps=self.n_steps, gamma=self.gamma, lam=self.lam)
TypeError: Can't instantiate abstract class Runner with abstract methods _run

**Comment by jhwangbo** [comment]
Please use raisimGymTorch that is included in the raisimLib repo. This repo is outdated. Only the ones from raisimTech are officially supported
